region                = "eu-west-1"
use_profile           = "pawel"
state_bucket_name     = "pawel-terraform-state"
artifacts_bucket_name = "pawel-alexa-cloud-control"
table_name            = "alexa-cloud-control-locks"
environment           = "development"